# Generated by Django 4.2.3 on 2023-12-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_Price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('IC', 'Ice Cream Cake'), ('CC', 'Choco Cake'), ('RC', 'Rainbow Cake'), ('FC', 'Fruit Cake'), ('SC', 'Strawberry Cake'), ('VC', 'Vannila Cake'), ('BC', 'Black forest Cake'), ('kC', 'KitKat Cake'), ('PC', 'Pinata Cake'), ('PU', 'Pullme Up Cake'), ('CU', 'Cup Cake'), ('CT', 'Choco Truffle Cake'), ('PS', 'Popsicle Cake'), ('DC', 'Donut Cake'), ('OC', 'Oreo Cake')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
